cmd /c color 0a
$DebugPreference="Continue"
cls
echo ""
echo "                         HHHHH  HH     AAA     CCCC   KK  KK         IIII   TTTTTTTTT"
echo "                            HH  HH    AA AA    CC     KK KK       ~   II       TT"
echo "                      ----  HHHHHH   AAAAAAA   CC     KKKK     ~~~    II       TT  ----"
echo "                            HH  HH   AA   AA   CC     KK KK   ~       II       TT"
echo "                            HH  HH   AA   AA   CCCC   KK  KK         IIII     TTTT"
echo ""
echo "                                          °°°°°°°°°°°°°°°°°°°°°°°°°"
echo "                                          °° HACK~IT  POWERSHELL °°"
echo "                                          °°    by Shadowmind    °°"
echo "                                          °°°°°°°°°°°°°°°°°°°°°°°°°"
echo ""
echo "                      °°°°°°°°°°°°°°°°°       °°°°°°°°°°°°°°°°°       °°°°°°°°°°°°°°°°°"
echo "                      °°         [ ] °°       °°         [ ] °°       °°         [ ] °°"
echo "                      °°°°°°°°°°°°°°°°°       °°°°°°°°°°°°°°°°°       °°°°°°°°°°°°°°°°°"
echo ""
echo "                      °°°°°°°°°°°°°°°°°       °°°°°°°°°°°°°°°°°       °°°°°°°°°°°°°°°°°"
echo "                      °°         [ ] °°       °°         [ ] °°       °°         [ ] °°"
echo "                      °°°°°°°°°°°°°°°°°       °°°°°°°°°°°°°°°°°       °°°°°°°°°°°°°°°°°"
echo ""
echo "                      °°°°°°°°°°°°°°°°°       °°°°°°°°°°°°°°°°°       °°°°°°°°°°°°°°°°°"
echo "                      °°         [ ] °°       °°         [ ] °°       °°         [ ] °°"
echo "                      °°°°°°°°°°°°°°°°°       °°°°°°°°°°°°°°°°°       °°°°°°°°°°°°°°°°°"
echo ""
echo "                      °°°°°°°°°°°°°°°°°       °°°°°°°°°°°°°°°°°       °°°°°°°°°°°°°°°°°"
echo "                      °°         [ ] °°       °°         [ ] °°       °° Exit    [X] °°"
echo "                      °°°°°°°°°°°°°°°°°       °°°°°°°°°°°°°°°°°       °°°°°°°°°°°°°°°°°"
echo ""
Write-Warning "This Project is in ALPHA Status. Instable!"
Write-Debug "v 0.1 (No features)"
pause